spring:
  kafka:
    product:
      bootstrap-servers: kafka:29029
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  product:product