spring:
  kafka:
    product:
      bootstrap-servers: localhost:8888
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  stock:stock